### ISSUE TITLE
Add support for Prism.js toolbar plugin

### ISSUE THREAD

**Issue by tempris** [PrismJS/live#14]
I have found that simply adding the following will enable the toolbar plugin for Prism.js to work with Prism-Live.js:

```css
/* Add support for prism toolbar. */

div.prism-live:hover .toolbar {
  opacity: 1;
}

div.prism-live .toolbar {
  z-index: 2;
}
```

I have added it as `prism-live-toolbar.css` to [a branch on my own fork](https://github.com/tempris/prismjs-live/tree/add-support-for-prism-toolbar-plugin) but is small so I am not sure if it justifies it being in its own file, unless it is better for people to be able to choose whether or not they want to include it into their own projects.

If you have time please let me know if this is acceptable for a merge request. Also should it be in a separate css file or in the main one?

Thanks for your time! #
